apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${appname}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ${appname}
  template:
    metadata:
      labels:
        app: ${appname}
    spec:
      containers:
      - name: ${appname}
        image: harishtiru/${appname}:v${BUILD_ID}
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ${appname}
spec:
  selector:
    app: ${appname}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: ${portno} # Choose any available port number between 30000 and 32767
  type: NodePort
